# -*- coding: utf-8 -*-
"""db/seed.sql を生成するスクリプト。内容を足したいときはここを編集して python3 db/_gen_seed.py を実行。"""

QUESTIONS = [
# (category, question, intent_ja)
("opening", "Tell me about yourself and what brings you here today.",
 "経歴の一貫性と、この職種に向かう筋道を60〜90秒で語れるか。羅列ではなく物語になっているかを見ている。"),
("opening", "Walk me through your CV, focusing on what is most relevant to this role.",
 "相手の関心に合わせて情報を取捨選択できるか。全部話そうとしていないか。"),
("opening", "How would your current manager describe you in three words?",
 "自己認識と、第三者視点で語れる客観性。抽象語のあとに根拠が続くかを見ている。"),
("opening", "What are you looking for in your next role?",
 "志望動機の軸。逃げの理由ではなく、向かう先が語れているか。"),
("opening", "Give me a quick overview of the size and shape of the portfolio you manage today.",
 "担当規模の具体性。件数・金額・顧客層を数字で答えられるか。"),

("motivation", "Why are you leaving your current position?",
 "前職批判に流れず、前向きな理由に変換できるか。NZでは特に建設的な語り口が重視される。"),
("motivation", "Why do you want to work for this company specifically?",
 "企業研究の深さ。どの会社にも言える答えになっていないか。"),
("motivation", "You are moving from travel into a different industry. Why the change, and why now?",
 "業界転換の説得力。持ち運べるスキルを言語化できているか。"),
("motivation", "What do you know about our customers and the problems they come to us with?",
 "顧客視点で準備してきたか。製品ではなく顧客の課題を語れるか。"),
("motivation", "Where do you see yourself in three years?",
 "定着の見込みと成長意欲のバランス。"),
("motivation", "What attracted you to customer success rather than sales?",
 "役割理解。既存顧客との長期関係構築という職能の本質を掴んでいるか。"),

("behavioural", "Tell me about a time you turned an unhappy customer into a satisfied one.",
 "STARで語れるか。状況説明が長すぎず、行動と結果に重心があるか。"),
("behavioural", "Describe a situation where you had to influence someone who did not report to you.",
 "権限のない相手を動かす力。CSM/AM職の中核能力。"),
("behavioural", "Tell me about a mistake you made at work and what you did about it.",
 "誠実さと学習能力。責任転嫁していないか、再発防止まで語れるか。"),
("behavioural", "Give me an example of when you had to manage competing deadlines.",
 "優先順位づけの判断基準を言語化できるか。"),
("behavioural", "Describe a time you disagreed with your manager. How did you handle it?",
 "健全な意見表明ができるか。NZの職場はフラットで、黙って従うだけの人は評価されにくい。"),
("behavioural", "Tell me about a process you improved. What was the measurable impact?",
 "改善マインドと定量化。数字が出てくるかが分かれ目。"),
("behavioural", "Tell me about a time you had to say no to a customer.",
 "期待値調整の力。断り方に配慮があるか。"),
("behavioural", "Describe a situation where you worked with a difficult stakeholder internally.",
 "社内調整力。相手を悪者にせず構造で語れるか。"),
("behavioural", "Tell me about a time you had to learn something complex quickly.",
 "学習スピードと自走力。未経験業界への転身では特に重要。"),
("behavioural", "Give an example of when you went beyond what was asked of you.",
 "期待を超える提案ができる人か。ただし自己犠牲の美談になっていないか。"),
("behavioural", "Tell me about a time you received difficult feedback. What did you do with it?",
 "フィードバック受容性。防御的になっていないか。"),
("behavioural", "Describe the most complex coordination you have run end to end.",
 "現職の強みである調整力を、規模と複雑さの具体で示せるか。"),

("csm_am", "How do you prioritise your portfolio when every account wants your attention?",
 "セグメンテーションの考え方。感覚ではなく基準で語れるか。"),
("csm_am", "Walk me through how you would run a quarterly business review with a key account.",
 "QBRの型を持っているか。アジェンダ・準備・フォローまで話せるか。"),
("csm_am", "How do you spot the early warning signs that an account is at risk of churning?",
 "先回りの発想。利用状況・関係性・組織変化などの兆候を挙げられるか。"),
("csm_am", "A major client tells you they are considering a competitor. What are your first three moves?",
 "危機対応の順序立て。まず聴く姿勢が最初に来るか。"),
("csm_am", "How do you approach a renewal conversation that you know will be difficult?",
 "更新交渉の準備と、価値の再提示ができるか。"),
("csm_am", "How do you identify an upsell opportunity without damaging trust?",
 "顧客の課題起点で提案できるか。押し売りになっていないか。"),
("csm_am", "Describe how you would onboard a new client in their first 90 days.",
 "オンボーディング設計。マイルストーンと成功指標を置けるか。"),
("csm_am", "How do you measure whether a customer is getting value from what they bought?",
 "アウトカム志向。利用量ではなく成果で測る発想があるか。"),
("csm_am", "Tell me how you build a relationship map inside a large client organisation.",
 "ステークホルダー・マッピング。単一窓口依存のリスクを理解しているか。"),
("csm_am", "A client escalates over your head to your manager. How do you respond?",
 "エスカレーション時の成熟度。感情的にならず関係を立て直せるか。"),
("csm_am", "How do you handle a customer request that your product or service simply cannot meet?",
 "誠実な期待値調整と代替案の提示。"),
("csm_am", "What does a healthy account look like to you, in numbers?",
 "健全性指標の理解。更新率・利用率・接触頻度などを挙げられるか。"),
("csm_am", "How would you handle handing over an account you have owned for years?",
 "属人化させない引き継ぎ設計。"),
("csm_am", "How do you work with sales, support and product teams to keep a client on track?",
 "部門横断の連携。自分の役割を結節点として語れるか。"),

("nz_context", "What is your current visa status and your right to work in New Zealand?",
 "採用側が最初に確認したい実務事項。簡潔に事実だけを、堂々と答える。"),
("nz_context", "What made you choose to build your career in New Zealand?",
 "定着意思の確認。生活基盤と将来設計が語れるか。"),
("nz_context", "How do you adapt your communication style when working across cultures?",
 "多文化職場での適応力。NZでは実例つきで語れると強い。"),
("nz_context", "Our team is quite informal and collaborative. How do you work in that kind of environment?",
 "フラットな職場文化への適合。上下関係前提の話し方になっていないか。"),
("nz_context", "How do you approach working respectfully with Māori and Pasifika clients or colleagues?",
 "文化的配慮の姿勢。知らないことは正直に、学ぶ意思を示す。"),
("nz_context", "English is not your first language. How do you make sure nothing gets lost with clients?",
 "弱みへの向き合い方。確認の工夫を具体的に語れるか。防御的にならないこと。"),
("nz_context", "What do you think is different about doing business in New Zealand compared with Japan?",
 "観察の深さ。ステレオタイプではなく実体験で語れるか。"),
("nz_context", "How do you handle the tall poppy dynamic when talking about your own achievements?",
 "NZでの自己PRの間合い。事実と数字で語り、誇張しない姿勢。"),

("competency", "How do you keep track of many moving parts without letting anything slip?",
 "正確性という強み。仕組みで担保していると語れるか。"),
("competency", "Tell me about your approach to negotiation.",
 "交渉観。勝ち負けではなく共通利益の設計として語れるか。"),
("competency", "How do you handle pressure and tight timelines?",
 "ストレス耐性。精神論ではなく具体的な対処法で。"),
("competency", "What would you do in your first 30, 60 and 90 days in this role?",
 "入社後の立ち上がり計画。聴く→整理する→動くの順序があるか。"),
("competency", "How do you use data in your day to day work?",
 "データリテラシー。何を見て何を判断したかの実例。"),
("competency", "Tell me about a time you had to deliver bad news to a client.",
 "誠実なコミュニケーション。早く・正直に・代替案とともに。"),

("closing", "What questions do you have for us?",
 "準備度が最も出る場面。役割・成功の定義・チームについて聞けるか。"),
("closing", "What are your salary expectations?",
 "市場相場の把握と、レンジで答える落ち着き。"),
("closing", "When would you be available to start?",
 "現職の通知期間を踏まえた現実的な回答。"),
("closing", "Is there anything we have not asked that you think we should know?",
 "最後の一押し。まだ伝えていない強みを一つ残しておけるか。"),
("closing", "Why should we hire you over other candidates?",
 "差別化。誇張せず、他の人が言えないことを言えるか。"),
]

PHRASES = [
# (term, meaning_ja, example, category)
("churn", "解約・離脱。顧客が契約を更新せず離れること", "We reduced churn by identifying at-risk accounts three months before renewal.", "csm_am"),
("retention", "維持率。既存顧客を継続させる度合い", "My focus has consistently been on retention rather than net new logos.", "csm_am"),
("renewal", "契約更新", "I own the renewal conversation from ninety days out.", "csm_am"),
("QBR (Quarterly Business Review)", "四半期ごとの顧客との振り返り会議。成果の確認と次期計画を行う", "I run a QBR with each key account to review outcomes against the goals we set.", "csm_am"),
("onboarding", "導入初期の立ち上げ支援", "A structured onboarding in the first ninety days is the strongest predictor of renewal.", "csm_am"),
("adoption", "顧客が実際にサービスを使いこなしている度合い", "Licences were sold, but adoption had stalled at about forty percent.", "csm_am"),
("upsell / cross-sell", "既存顧客への追加販売／関連商品の販売", "The upsell came out of a problem they raised, not from a target I had to hit.", "csm_am"),
("account health", "アカウントの健全性。継続可能性を示す総合指標", "I track account health across usage, sentiment and executive engagement.", "csm_am"),
("book of business / portfolio", "自分が担当する顧客群", "I managed a portfolio of thirty-two corporate accounts.", "csm_am"),
("net revenue retention", "既存顧客からの収益維持率。100%超は既存顧客が成長している状態", "Net revenue retention is the number I would want to be measured on.", "csm_am"),
("escalation", "上位者・上位部門への引き上げ対応", "I escalated early rather than letting the issue sit with me.", "csm_am"),
("stakeholder mapping", "顧客組織内の関係者と影響力を可視化すること", "Single-threaded accounts are fragile, so I map at least three contacts per client.", "csm_am"),
("champion", "顧客社内で自社を推してくれるキーパーソン", "I identified a champion in operations who could speak for us internally.", "csm_am"),
("decision maker", "最終決裁者", "I made sure I had access to the decision maker well before the renewal date.", "csm_am"),
("touchpoint", "顧客との接点", "I set a cadence of touchpoints rather than waiting for problems to surface.", "csm_am"),
("cadence", "定期的な頻度・リズム", "We agreed a monthly cadence with a quarterly deep dive.", "csm_am"),
("SLA (Service Level Agreement)", "サービス水準の合意", "We were consistently inside our SLA, but the client still felt unsupported.", "csm_am"),
("time to value", "顧客が価値を実感するまでの時間", "Shortening time to value was the single biggest lever we had.", "csm_am"),
("customer lifecycle", "顧客の導入から更新までの一連の流れ", "I look at the whole customer lifecycle, not just the renewal window.", "csm_am"),
("voice of the customer", "顧客の声を社内に届ける活動", "I acted as the voice of the customer in our product prioritisation meetings.", "csm_am"),
("root cause", "根本原因", "We fixed the root cause rather than the symptom.", "problem_solving"),
("pain point", "顧客が抱える具体的な困りごと", "Their real pain point was internal reporting, not the service itself.", "problem_solving"),
("workaround", "暫定的な回避策", "I offered a workaround the same day and a permanent fix within the fortnight.", "problem_solving"),
("scope creep", "当初の範囲を超えて仕事が膨らむこと", "I flagged scope creep early and reset expectations with the client.", "problem_solving"),
("expectation management", "期待値の調整", "Most escalations I have seen come down to expectation management.", "problem_solving"),
("trade-off", "何かを取れば何かを諦める関係", "I was transparent about the trade-off between speed and accuracy.", "problem_solving"),
("bottleneck", "全体の流れを詰まらせている箇所", "The bottleneck was approval, not capacity.", "problem_solving"),
("mitigate", "リスクや影響を和らげる", "To mitigate the risk, I built a second point of contact into the account.", "problem_solving"),
("streamline", "無駄を省いて効率化する", "I streamlined the booking process from eleven steps to six.", "improvement"),
("baseline", "改善前の基準値", "Against a baseline of four days, we brought it down to one.", "improvement"),
("lead time", "着手から完了までの所要時間", "Lead time dropped by roughly forty percent.", "improvement"),
("throughput", "一定時間あたりの処理量", "The same team handled higher throughput without extra headcount.", "improvement"),
("end to end", "最初から最後まで一気通貫で", "I owned the process end to end.", "improvement"),
("cross-functional", "部門横断の", "It was a cross-functional effort across operations, finance and sales.", "improvement"),
("buy-in", "関係者の賛同・協力の取り付け", "I got buy-in from the team before rolling the change out.", "influence"),
("align", "認識や方向性を揃える", "I aligned the client and our operations team on a single set of priorities.", "influence"),
("push back", "反対意見を示す・押し返す", "I pushed back respectfully and explained the impact on delivery.", "influence"),
("influence without authority", "権限を持たずに人を動かす力", "Most of my work has been influencing without authority.", "influence"),
("navigate", "複雑な状況をうまく渡っていく", "I had to navigate competing priorities between two departments.", "influence"),
("bring someone along", "相手を巻き込んで一緒に進める", "I brought the wider team along rather than deciding on my own.", "influence"),
("take ownership", "自分ごととして責任を持つ", "I took ownership of the error and communicated it the same morning.", "attitude"),
("trusted advisor", "単なる担当者ではなく相談される存在", "My aim is to be a trusted advisor, not just a point of contact.", "attitude"),
("proactive", "受け身ではなく先回りする", "I would rather be proactive than firefight.", "attitude"),
("hands-on", "実務に自分で手を動かして関わる", "I am comfortable being hands-on while also seeing the bigger picture.", "attitude"),
("can-do attitude", "前向きに取り組む姿勢。NZの求人票で頻出", "The role called for a can-do attitude and a willingness to muck in.", "nz_workplace"),
("muck in", "みんなで手を動かして協力する（NZ口語）", "In a small team everyone mucks in.", "nz_workplace"),
("sort it out", "対処する・片づける（NZ口語）", "I would rather sort it out than pass it on.", "nz_workplace"),
("across (be across something)", "内容を把握している（NZ/豪でよく使う）", "I made sure I was across every account before the handover.", "nz_workplace"),
("touch base", "軽く連絡を取る・状況を確認する", "I will touch base with them before the end of the week.", "nz_workplace"),
("catch up", "打ち合わせ・情報交換（NZでは会議の意味で頻出）", "We have a weekly catch up with the operations team.", "nz_workplace"),
("keen", "乗り気である・意欲がある（NZで非常に頻出）", "I am keen to move into a role where I own the relationship long term.", "nz_workplace"),
("whānau", "マオリ語で家族・広い意味での仲間。職場でも使われる", "The team culture felt like whānau, which mattered to me.", "nz_workplace"),
("Aotearoa", "ニュージーランドのマオリ語名", "I have built my career here in Aotearoa since completing my Master's.", "nz_workplace"),
("tall poppy syndrome", "突出した人を叩く風潮。NZでは自慢しすぎない語り方が好まれる", "I let the numbers speak rather than overselling myself.", "nz_workplace"),
("notice period", "退職までの通知期間", "I am on a four-week notice period.", "logistics"),
("right to work", "就労資格", "I hold a Post Study Work Visa, so I have full right to work in New Zealand.", "logistics"),
("remuneration package", "給与を含む待遇一式", "I would be looking at a remuneration package in the range of ...", "logistics"),
("in the region of", "およそ〜くらい（給与を柔らかく伝える言い方）", "I am looking for something in the region of eighty thousand.", "logistics"),
("I would say ...", "断定を避けて意見を述べる緩衝表現", "I would say the biggest lever was earlier communication.", "hedging"),
("from my experience ...", "自分の経験に限定して語る前置き", "From my experience, most escalations are avoidable.", "hedging"),
("what worked well for me was ...", "自慢に聞こえにくい成果の語り方", "What worked well for me was setting the agenda before the meeting.", "hedging"),
("I am still learning ...", "未熟な領域を正直に認める言い方", "I am still learning the insurance side, and I am deliberately going at it fast.", "hedging"),
("to give you a sense of scale ...", "規模感を示す前置き", "To give you a sense of scale, that was around two hundred bookings a month.", "hedging"),
("the reason I ask is ...", "質問の意図を添えて印象を柔らげる", "The reason I ask is that I want to understand how success is measured here.", "hedging"),
("STAR method", "Situation・Task・Action・Result の順で答える行動面接の型", "I structure behavioural answers using the STAR method.", "interview_technique"),
("in a nutshell", "要するに・手短に言えば", "In a nutshell, I keep relationships from going quiet.", "interview_technique"),
("that said ...", "とはいえ（前言を和らげて転換する）", "That said, I would want to understand your renewal cycle first.", "interview_technique"),
]

def q(s):
    return "'" + s.replace("'", "''") + "'"

lines = []
lines.append("-- 自動生成ファイル。編集する場合は db/_gen_seed.py を直してから再生成してください。")
lines.append("DELETE FROM questions WHERE source = 'seed';")
lines.append("DELETE FROM phrases WHERE source = 'seed';")
lines.append("")
for cat, text, intent in QUESTIONS:
    lines.append("INSERT INTO questions (category, text, intent, source) VALUES (%s, %s, %s, 'seed');"
                 % (q(cat), q(text), q(intent)))
lines.append("")
for term, meaning, example, cat in PHRASES:
    lines.append("INSERT OR IGNORE INTO phrases (term, meaning_ja, example, category, source) VALUES (%s, %s, %s, %s, 'seed');"
                 % (q(term), q(meaning), q(example), q(cat)))

with open("db/seed.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("questions:", len(QUESTIONS), " phrases:", len(PHRASES))
